apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
    application: dockercoins
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  strategy: {}
  template:
    metadata:
      labels:
        app: worker
        application: dockercoins
    spec:
      containers:
      - image: slickteam/dockercoins-worker:v0.1
        name: worker
        readinessProbe:
            exec:
              command:
                - curl
                - -X 
                - "ceci est un test"
                - http://hasher