apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
        volumeMounts:
          - mountPath: "/usr/share/nginx/html"
            name: nginx-root

      volumes:
        - name: nginx-root
          persistentVolumeClaim:
              claimName: nginx-root-pvc
