apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
      tier: frontend
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: slickteam/guestbook-frontend:v1.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http-server
          containerPort: 8080
        resources: {}
        env:
        - name: PORT
          value: "8080"
        - name: GUESTBOOK_API_ADDR
          value: guestbook-backend:8080
