apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-backend
  labels:
    app: guestbook
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
      tier: backend
  template:
    metadata:
      labels:
        app: guestbook
        tier: backend
    spec:
     initContainers:
      - name: init-db-ready
        image: mongo:4
        command: ['/bin/sh', '-c']
        args:
          - echo "Waiting for mongodb to start...";until (mongo --host guestbook-mongodb:27017 >/dev/null 2>&1) do echo "Waiting for connection for 2 sec."; sleep 2; done
     containers:
      - name: backend
        image: slickteam/guestbook-backend:v1.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http-server
          containerPort: 8080
        resources: {}
        env:
        - name: PORT
          value: "8080"
        - name: GUESTBOOK_DB_ADDR
          value: "guestbook-mongodb:27017"
