################################################################################
# WARNING: This MongoDB deployment is not suitable for production as the data is
# not persistently stored and will go away every time the Pod restarts. Consider
# using a Helm chart that provisions a StatefulSet instead of Deployment.
################################################################################
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: guestbook-mongodb
  labels:
    app: guestbook
    tier: db
spec:
  serviceName: guestbook-mongodb
  replicas: 3
  selector:
    matchLabels:
      app: guestbook
      tier: db
  template:
    metadata:
      labels:
        app: guestbook
        tier: db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo:4
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
          command:
            - mongod
            - "--bind_ip_all"
            - "--replSet"
            - rs0
        # Ce conteneur "sidecar" permet de configurer mongodb automatiquement
        - name: mongo-sidecar
          image: cvallance/mongo-k8s-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "app=guestbook,tier=db"
            - name: KUBERNETES_MONGO_SERVICE_NAME
              value: guestbook-mongodb
  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
        labels:
          app: guestbook
          tier: db
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi