
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: mongodb-data-pvc 
 labels:
   app: guestbook
   tier: db
spec:
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
     storage: 100Mi